ignore_index: 255
classes:
  - name: background
    train_id: 0
    raw_ids: [0]
    color: [0, 0, 0]
  - name: river
    train_id: 1
    raw_ids: [10]
    color: [0, 45, 180]
  - name: stream
    train_id: 2
    raw_ids: [11]
    color: [0, 145, 255]
  - name: creek
    train_id: 3
    raw_ids: [12]
    color: [185, 235, 255]
  - name: wetland
    train_id: 4
    raw_ids: [13]
    color: [235, 170, 235]
  - name: wet_forest
    train_id: 5
    raw_ids: [14]
    color: [120, 50, 160]
  - name: lake
    train_id: 6
    raw_ids: [16]
    color: [0, 210, 210]
ignored:
  - name: oxbow
    raw_ids: [15]
    color: [255, 150, 0]
  - name: canal
    raw_ids: [17]
    color: [0, 170, 0]
